languages:
  Ruby: true
  JavaScript: false
  PHP: false
engines:
  markdownlint:
    enabled: true
  rubocop:
    enabled: true
  brakeman:
   	enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
  	enabled: true
exclude_paths:
  app/assets/**
