language: ruby
rvm:
- 2.3.0
- 2.2.4
bundler_args: --jobs=2
script:
script:
  - bundle exec rake db:setup
  - bundle exec rspec
cache: bundler
services:
  - postgresql
addons:
  postgresql: "9.4"
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
# uncomment and edit the following line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
