language: ruby
rvm:
  - 2.2
env:
  - DB=postgresql
script: 
  - bundle exec rake db:test:prepare
  - bundle exec rspec spec/
before_script:
  - psql -c 'create database my_app_test' -U postgres
bundler_args: --binstubs=./bundler_stubs
# uncomment and edit the following line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
